name: vschttpd
description: |
  Local development server with support for running
  flutter web application in vscode webview extensions
repository: https://github.com/zoocityboy/vschttpd
issue_tracker: https://github.com/zoocityboy/vschttpd/issues
version: 1.0.0+2
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  args: ^2.3.0
  shelf: ^1.2.0
  shelf_static: ^1.1.0
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.3
executables:
  vschttpd:
