name: vschttpd
description: |
  Local development server with support for running
  web application in vscode webview extensions

version: 1.0.0
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  args: ^2.3.0
  build_cli_annotations: ^2.0.0
  shelf: ^1.2.0
  shelf_static: ^1.1.0
  path: ^1.8.0

dev_dependencies:
  build_cli: ^2.1.3
  build_runner: ^2.1.4
  build_verify: ^2.0.0

  test: ^1.19.3
executables:
  vschttpd:
